config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'pages#home'
  get 'pages/admins'
  get 'pages/users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/admins.html.erb
<div>
  <h1>This is Admin Page</h1>
  <h1>Welcome <%= @admin_email %></h1>
</div>
<p>Your User Type is: <%= @user_type%></p>
<h1>Return</h1>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<div class = 'container'>
  <% if user_signed_in? %>
    <h3>User Sign Out</h3>
    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }%></li>
    <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
  <% elsif !admin_signed_in? %>
    <h3>User Sign In</h3>
    <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <li><%= link_to "Sign In", new_user_session_path %></li>
  <% end %>
</div>
<div class = 'container'>
  <% if admin_signed_in? %>
    <h3>Admin Sign Out</h3>
    <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete, data: { turbo_method: :delete }%></li>
    <li><%= link_to "Edit Profile", edit_admin_registration_path %></li>
  <% elsif !user_signed_in? %>
    <h3>Admin Sign In</h3>
    <li><%= link_to "Sign Up", new_admin_registration_path %></li>
    <li><%= link_to "Sign In", new_admin_session_path %></li>
  <% end %>
</div>
<div class = 'container'>
  <h3>Page Links</h3>
  <% if admin_signed_in? %>
    <li><%= link_to "User Path", pages_users_path %></li>
    <li><%= link_to "Admin Path", pages_admins_path %></li>
  <% elsif user_signed_in? %>
    <li><%= link_to "User Path", pages_users_path %></li>
  <% elsif !user_signed_in? %>
    <li><%= link_to "Sign Up", new_admin_registration_path %></li>
    <li><%= link_to "Sign In", new_admin_session_path %></li>
  <% end %>
</div>

app/views/pages/users.html.erb
<div>
  <h1>This is Users Page</h1>
  <h1>Welcome User: <%= @user_email%></h1>
</div>
<p>Your User Type is: <%= @user_type%></p>
<h1>Return</h1>
<%= link_to "Home", root_path %>